# Use Ubuntu as the build stage
FROM openjdk:17-jdk-alpine AS build
# Set the working directory
WORKDIR /app
# Copy the source code into the container
COPY . .
# Build the application using Maven
RUN ./mvnw clean package -DskipTests

# Use a more lightweight runtime image for the final stage
FROM openjdk:17-jdk-alpine AS runtime
# Set the working directory in the final image
WORKDIR /app
# Copy the jar file from the builder stage
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar
# Expose the port the application runs on
EXPOSE 8080

# Start the application
ENTRYPOINT ["java", "-jar", "/app/demo.jar"]
